<a href="https://colab.research.google.com/github/AdrianHarman/DLrepo/blob/master/localdp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [0]:
def create_db_pds(n_entries):
  db = torch.rand(n_entries)>0.5
  
  def get_pdb(db, rm_index):
    return torch.cat((db[0:rm_index],
                      db[rm_index+1:]))
  parallel_dbs = list()
  
  for i in range(len(db)):
    pdb = get_pdb(db, i)
    parallel_dbs.append(pdb)
  
  return db, parallel_dbs

In [9]:
db, pdbs = create_db_pds(10)
db  

tensor([0, 1, 1, 1, 1, 0, 0, 0, 0, 1], dtype=torch.uint8)

In [10]:
def query(db, threshold=5):
  return (db.sum() > threshold).float()

query(db)

tensor(0.)

In [0]:
db, pdbs = create_db_pds(10)

In [0]:
db

tensor([1, 0, 1, 0, 0, 0, 0, 1, 1, 0], dtype=torch.uint8)

In [13]:
fcf = torch.rand(10)>0.5
fcf

tensor([1, 1, 0, 1, 0, 1, 1, 1, 1, 0], dtype=torch.uint8)

In [14]:
scf = torch.rand(10)>0.5
scf

tensor([1, 0, 1, 0, 1, 0, 1, 0, 0, 0], dtype=torch.uint8)

In [15]:

augmented_db = db.float() * fcf.float() + (1-fcf.float())*scf.float()
augmented_db

tensor([0., 0., 1., 0., 1., 0., 1., 0., 0., 0.])